### ISSUE TITLE
Implement metrics file for Java repositories files

### ISSUE THREAD

**Issue by zuoqin** [yegor256/aibolit#12]

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@zuoqin[/z](https://www.0crat.com/u/zuoqin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT5UB7XAP) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#12` is not assigned, can't get performer
