### ISSUE TITLE
The Setter pattern shouldn't look at asserts

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#121]
As discussed in https://github.com/yegor256/aibolit/issues/92 with @yegor256 there is a pattern with assert:
```
public Builder setScope(AclEntryScope scope) {
  assert !x;
  this.scope = scope;
}
```

We should find those cases

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by silverCase** [comment]
Will do

**Comment by 0crat** [comment]
The job [#121](https://github.com/yegor256/aibolit/issues/121) assigned to @silvercase[/z](https://www.0crat.com/u/silvercase), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/67842526-b189-474e-b42c-e32fec3704db); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @silvercase[/z](https://www.0crat.com/u/silvercase) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@silvercase[/z](https://www.0crat.com/u/silvercase) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @silvercase[/z](https://www.0crat.com/u/silvercase) resigned from [#121](https://github.com/yegor256/aibolit/issues/121), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#121](https://github.com/yegor256/aibolit/issues/121) assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/55e513d5-39e9-499a-a094-254eb762a0cf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by tribals** [comment]
@lyriccoder The pattern is still not clear. According to your example:

```java
public Builder setScope(AclEntryScope scope) {
  assert !x;
  this.scope = scope;
}
```

But this is simply not a valid code. What is a `x` variable? Was it passed to setter? No. Then from where it comes?

Also, this is not clear what "The Setter pattern shouldn't look at asserts" means ever. As I understood, `classic_setter` matches when method name starts with `set` following member variable name and the body of method is only assignment. Does it mean that it shouldn't match when there is also `assert` in method body? If so, why it shouldn't match? An `assert` doesn't change semantics of method. Also, isn't that the `assert` is forbidden ever?

**Comment by 0crat** [comment]
@tribals[/z](https://www.0crat.com/u/tribals) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by tribals** [comment]
@0crat wait

**Comment by tribals** [comment]
@lyriccoder Please, read my comment above.
