### ISSUE TITLE
Bring static type checking for whole project

### ISSUE THREAD

**Issue by tribals** [yegor256/aibolit#130]
Python is dynamically typed language. But there is [ongoing work](https://docs.python.org/3/library/typing.html) for bringing static type checking to it.

The static type checking consists of two parts: type hints and third-party static type checkers (linters).

Let's take a closer look to both parts.

Type hints, well, is just hints. They are simple annotations of source code which explain what type of variables, function parameters and return values is expected. Python interpreter by itself simply *ignores it at all*.

Type checkers are third-party tools which do actual processing of these hints, and produce a result - is these types fulfilled or not. A couple of examples: [mypy](http://mypy-lang.org/), [pyright](https://github.com/microsoft/pyright).

So, in order to benefit from static typing you must do the both. Annotating sources with type hints is worthless at it's own. Even worse, without checking these annotations can be misleading.

So, the decision here is either "annotate and check" or "don't even bother with it".

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@tribals I agree

**Comment by acheshkov** [comment]
@0crat in

**Comment by acheshkov** [comment]
@0crat assign @tribals

**Comment by 0crat** [comment]
> @0crat assign @tribals  ([here](https://github.com/yegor256/aibolit/issues/130#issuecomment-607297750))

@acheshkov The job [#130](https://github.com/yegor256/aibolit/issues/130) assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/c779793e-541f-49a3-b09a-150d0bc7d5a3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@tribals[/z](https://www.0crat.com/u/tribals) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by tribals** [comment]
Done
