### ISSUE TITLE
array_as_argument pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#136]
Here it is:

```
class Foo {
  void bar(int[] x) { // here
  }
}
```

If we pass an array as an argument, it's a pattern. It's better to use objects, instead of arrays.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#136](https://github.com/yegor256/aibolit/issues/136) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/79da8fca-5a12-43f3-8639-24d8ee41f8a8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@yegor256 merged, please close

**Comment by paulodamaso** [comment]
@0crat wait for closure

**Comment by paulodamaso** [comment]
@acheshkov please close

**Comment by paulodamaso** [comment]
@acheshkov ping

**Comment by paulodamaso** [comment]
@yegor256 ping

**Comment by paulodamaso** [comment]
@0crat status

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/aibolit/issues/136#issuecomment-617360798))

@paulodamaso This is what I know about this job in CT5UB7XAP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#136](https://github.com/yegor256/aibolit/issues/136) is [in scope](http://www.zerocracy.com/policy.html#14) for 19days
  * The role is `DEV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [11days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT5UB7XAP?q=%7Bjob%3A%27gh%3Ayegor256%2Faibolit%23136%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@acheshkov Looks like 0crat didn't detected the job has closed, please take a look

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/aibolit/issues/136#issuecomment-618998479))

@paulodamaso This is what I know about this job in CT5UB7XAP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#136](https://github.com/yegor256/aibolit/issues/136) is [in scope](http://www.zerocracy.com/policy.html#14) for 22days
  * The role is `DEV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [13days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT5UB7XAP?q=%7Bjob%3A%27gh%3Ayegor256%2Faibolit%23136%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@acheshkov please remove it from scope (try `@0crat out`)

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/aibolit/issues/136#issuecomment-619420980); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#136` is not assigned, can't get performer
