### ISSUE TITLE
loop_outsider pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#138]
Here it is:

```java
class Foo {
  void foo() {
    int x = 0;
    while (true) {
      x++; // here
    }
  }
}
```

Once we modify a variable, which is declared outside of the scope of the loop, it's a pattern.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#138](https://github.com/yegor256/aibolit/issues/138) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/e1741f61-d860-4454-ba06-8490cbed5804); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@acheshkov Merged, please close

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/aibolit/issues/138#issuecomment-625529088))

@paulodamaso This is what I know about this job in CT5UB7XAP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#138](https://github.com/yegor256/aibolit/issues/138) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT5UB7XAP?q=%7Bjob%3A%27gh%3Ayegor256%2Faibolit%23138%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@acheshkov I did not received payment for this one, please take a look

**Comment by paulodamaso** [comment]
@acheshkov ping

**Comment by paulodamaso** [comment]
@acheshkov Please take a look at this, I didn't received my payment

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/138#issuecomment-633610988))

@acheshkov Job `gh:yegor256/aibolit#138` is not assigned, can't get performer
