### ISSUE TITLE
var_siblings pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#141]
Here it is:

```java
class Foo {
  void bar() {
    int fileSize = 10;
    Date fileDate = new Date();
  }
}
```

Here `fileSize` and `fileDate` are "siblings" because they both have `file` as first part of their compound names. This is not a good practice, I believe. It's better to rename them to `size` and `date`.

`file` and `fileSize` are NOT siblings.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#141](https://github.com/yegor256/aibolit/issues/141) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/1c59b4fe-f3e2-4fca-8c93-b6d9db42ca25); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@acheshkov merged, please close

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#284](https://github.com/yegor256/aibolit/issues/284) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#284](https://github.com/yegor256/aibolit/issues/284) is solved here.
