### ISSUE TITLE
mutable_class pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#144]
If we see a class that has at least one non-`final` attribute, it's a mutable class. It's a good practice to make all classes immutable: https://www.yegor256.com/2014/06/09/objects-should-be-immutable.html

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#144](https://github.com/yegor256/aibolit/issues/144) assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/043f81c8-1c26-4a46-a3db-c645e9758c3a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@tribals[/z](https://www.0crat.com/u/tribals) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @tribals[/z](https://www.0crat.com/u/tribals) resigned from [#144](https://github.com/yegor256/aibolit/issues/144), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#144](https://github.com/yegor256/aibolit/issues/144) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/ef8380f5-d8bd-41f0-9c4e-6d9b74d91751); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by lyriccoder** [comment]
isn't it a duplicate of https://github.com/yegor256/aibolit/issues/118?
Seems absolutely the same patterns

**Comment by yegor256** [comment]
@lyriccoder yes, it's a dup of #118

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@acheshkov @lyriccoder @yegor256 What about my payment for the PR?

**Comment by acheshkov** [comment]
@paulodamaso we are handling, don't worry

**Comment by acheshkov** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/aibolit/issues/144#issuecomment-628499966))

@acheshkov This is what I know about this job in CT5UB7XAP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#144](https://github.com/yegor256/aibolit/issues/144) is [in scope](http://www.zerocracy.com/policy.html#14) for 23days
  * The role is `DEV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [6days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @tribals[/z](https://www.0crat.com/u/tribals): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT5UB7XAP?q=%7Bjob%3A%27gh%3Ayegor256%2Faibolit%23144%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by acheshkov** [comment]
@0crat out

**Comment by acheshkov** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/144#issuecomment-628505684))

@acheshkov The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/aibolit/issues/144#issuecomment-628508801))

@acheshkov This is what I know about this job in CT5UB7XAP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#144](https://github.com/yegor256/aibolit/issues/144) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT5UB7XAP?q=%7Bjob%3A%27gh%3Ayegor256%2Faibolit%23144%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by acheshkov** [comment]
@0crat pay 30min @paulodamaso

**Comment by paulodamaso** [comment]
@acheshkov Thanks!

**Comment by acheshkov** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/aibolit/issues/144#issuecomment-629018916))

@acheshkov This is what I know about this job in CT5UB7XAP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#144](https://github.com/yegor256/aibolit/issues/144) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT5UB7XAP?q=%7Bjob%3A%27gh%3Ayegor256%2Faibolit%23144%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
