### ISSUE TITLE
non_final_attribute pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#145]
Here it is:

```java
class Foo {
  private int x; // here!
}
```

Once we see an attribute that doesn't have `final` modifier, it's a pattern.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@acheshkov @yegor256 seems like a duplicate of #118

**Comment by yegor256** [comment]
@paulodamaso indeed, my bad, sorry

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#145` is not assigned, can't get performer
