### ISSUE TITLE
send_null pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#148]
Here it is:

```java
class Foo {
  void bar() {
    FileUtils.doIt(null); // here
  }
}
```

Once we see that `null` is being given as an argument to some method, it's a pattern.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by silverCase** [comment]
Can I take it?

**Comment by acheshkov** [comment]
@silverCase yes, assigned.

**Comment by 0crat** [comment]
The job [#148](https://github.com/yegor256/aibolit/issues/148) assigned to @silvercase[/z](https://www.0crat.com/u/silvercase), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/a43fd4bd-9042-44f6-b0f5-096eea8287fe); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @silvercase[/z](https://www.0crat.com/u/silvercase) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by silverCase** [comment]
@yegor256 What if we see something like that?
`    private String getWarningMessage(String key) {
      return getWarningMessage(key, null);
    }`
Is this recognized as a pattern?

**Comment by silverCase** [comment]
@yegor256 Is this recognized as a valid pattern?
'''
  public static void addDeprecation(String key, String[] newKeys) {
    addDeprecation(key, newKeys, null);
  }
'''
When not only null is given as an argument.

**Comment by 0crat** [comment]
@silvercase[/z](https://www.0crat.com/u/silvercase) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @silvercase[/z](https://www.0crat.com/u/silvercase) resigned from [#148](https://github.com/yegor256/aibolit/issues/148), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#148](https://github.com/yegor256/aibolit/issues/148) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/d2b50d58-5f22-41fa-bca6-efb1db6bc8c4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 24 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
