### ISSUE TITLE
ast.py:14-17: Introduce tests for AST.value method....

### ISSUE THREAD

**Issue by 0pdd** [yegor256/aibolit#158]
The puzzle `131-820bc5fe` from #131 has to be resolved: 

https://github.com/yegor256/aibolit/blob/077cb76d4798cb3cf580a5e538d1132eea6c59e9/aibolit/utils/ast.py#L14-L17

The puzzle was created by paulodamaso on 02-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#158](https://github.com/yegor256/aibolit/issues/158) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/a2750a8c-d246-4905-9b50-29eba0d683f3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@acheshkov 0pdd did not closed, please take a look

**Comment by paulodamaso** [comment]
@0crat wait for closure

**Comment by paulodamaso** [comment]
@acheshkov ping
