### ISSUE TITLE
var_middle.py:70-73: Lines implementation of Ast this...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/aibolit#160]
The puzzle `131-15497229` from #131 has to be resolved: 

https://github.com/yegor256/aibolit/blob/077cb76d4798cb3cf580a5e538d1132eea6c59e9/aibolit/patterns/var_middle/var_middle.py#L70-L73

The puzzle was created by paulodamaso on 02-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat  in

**Comment by 0crat** [comment]
The job [#160](https://github.com/yegor256/aibolit/issues/160) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/62cc5f38-f077-4d54-96ce-eb3d10f9a944); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@acheshkov Something bad happened here also, 0pdd did not closed the issue, please take a look

**Comment by paulodamaso** [comment]
@0crat wait for closure

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/aibolit/issues/160#issuecomment-619421423))

@paulodamaso This is what I know about this job in CT5UB7XAP, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#160](https://github.com/yegor256/aibolit/issues/160) is [in scope](http://www.zerocracy.com/policy.html#14) for 22days
  * The role is `DEV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [11days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT5UB7XAP?q=%7Bjob%3A%27gh%3Ayegor256%2Faibolit%23160%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@acheshkov still assigned to me, please try `@0crat out`

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/aibolit/issues/160#issuecomment-619431761); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)
