### ISSUE TITLE
Metric: Maximum length of the path between identifiers in AST

### ISSUE THREAD

**Issue by Vitaly-Protasov** [yegor256/aibolit#167]
Here I'll try to overview an idea of the mentioned metric at the topic.

Our purpose is to get the maximum size of the path between leaves in AST. 
It can be conducted by traversing through the AST of code snippet.

Let's consider an example at  the code snippet and its AST representation:
![image](https://user-images.githubusercontent.com/43099602/78655840-33275300-78cf-11ea-8432-bb3c960bfce7.png)

### As the examples you can considere color paths:
* lenght of the **green** one is 5
* lenght of the **yellow** one is 5
* of the **blue** one is 8
* of the **red** one is 10
* etc for others

### Max lenght of paths between leaves at this code snippet is **12**
*  Object -> Class -> Parameter -> MethodDecl -> Block -> Foreach -> Block -> IfStmt -> Block -> Return -> BooleanExpr -> true
* target -> VarDeclId-> Parameter -> MethodDecl -> Block -> Foreach -> Block -> IfStmt -> Block -> Return -> BooleanExpr -> true

**The same should work and for Class object.**

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#167](https://github.com/yegor256/aibolit/issues/167) assigned to @vitaly-protasov[/z](https://www.0crat.com/u/vitaly-protasov), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/6fbcdb42-c55f-4233-a75b-70096ea95822); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @vitaly-protasov[/z](https://www.0crat.com/u/vitaly-protasov) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job
