### ISSUE TITLE
Metric: Max Depth of AST

### ISSUE THREAD

**Issue by silverCase** [yegor256/aibolit#169]
### Max Depth of AST
Using the AST representation of code snippet below we can introduce a new metric:

```java
boolean f(Set<String> set, String value) {
    for (String entry : set) {
        if (entry.equalsIgnoreCase(value)) {
            return true;
        }
    }
    return false;
}
```
This AST for this snippet will look like this:

![image](https://user-images.githubusercontent.com/57872461/78678728-06386780-78f2-11ea-9852-4e021be0c591.png)

Rectangle objects are determined as terminals, elliptic objects are nonterminals, referring to code2seq [paper](https://arxiv.org/pdf/1808.01400.pdf).
### We are looking for is the max depth (_height_ in the graph theory) of AST.
Here it would be:
_Method Declaration → BlockStmt  → ForeachStmt → BlockStmt → IfStmt → BlockStmt → ReturnStmt_
And the number is 7.
**The greater the maximum depth, the worse the snippet rating.**

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#169](https://github.com/yegor256/aibolit/issues/169) assigned to @silvercase[/z](https://www.0crat.com/u/silvercase), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/801f2c37-957f-43dd-9169-ea0c86167e1b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @silvercase[/z](https://www.0crat.com/u/silvercase) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@silvercase[/z](https://www.0crat.com/u/silvercase) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.
