### ISSUE TITLE
multiple try patterns doesn't differ the same method with different class names

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#170]
Test should return empty array for this class:

[ServiceEntry.txt](https://github.com/yegor256/aibolit/files/4445460/ServiceEntry.txt)

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#170` is not assigned, can't get performer
