### ISSUE TITLE
Metric: number of external methods called by all the methods in the class

### ISSUE THREAD

**Issue by lukyanoffpashok** [yegor256/aibolit#183]
In the methods in the class an external method for this class can be called. So number of external methods called by all the methods in the class is suggested as a metric.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#183](https://github.com/yegor256/aibolit/issues/183) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/deb039c5-933b-4c17-b630-d43380e61d1f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@lukyanoffpashok PR merged, please close

**Comment by paulodamaso** [comment]
@0crat wait for closure

**Comment by paulodamaso** [comment]
@acheshkov @lukyanoffpashok please close, PR had already been merged

**Comment by 0pdd** [comment]
@lukyanoffpashok 2 puzzles [#285](https://github.com/yegor256/aibolit/issues/285), [#286](https://github.com/yegor256/aibolit/issues/286) are still not solved.

**Comment by 0pdd** [comment]
@lukyanoffpashok 2 puzzles [#488](https://github.com/cqfn/aibolit/issues/488), [#489](https://github.com/cqfn/aibolit/issues/489) are still not solved.

**Comment by 0crat** [comment]
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
I'm not managing `cqfn/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@lukyanoffpashok 2 puzzles [#740](https://github.com/cqfn/aibolit/issues/740), [#741](https://github.com/cqfn/aibolit/issues/741) are still not solved; solved: [#488](https://github.com/cqfn/aibolit/issues/488), [#489](https://github.com/cqfn/aibolit/issues/489).

**Comment by 0pdd** [comment]
@lukyanoffpashok the puzzle [#740](https://github.com/cqfn/aibolit/issues/740) is still not solved; solved: [#488](https://github.com/cqfn/aibolit/issues/488), [#489](https://github.com/cqfn/aibolit/issues/489), [#741](https://github.com/cqfn/aibolit/issues/741).

**Comment by 0pdd** [comment]
@lukyanoffpashok all 4 puzzles are solved here: [#488](https://github.com/cqfn/aibolit/issues/488), [#489](https://github.com/cqfn/aibolit/issues/489), [#740](https://github.com/cqfn/aibolit/issues/740), [#741](https://github.com/cqfn/aibolit/issues/741).
