### ISSUE TITLE
SpaceCounter fails for file with 0 or 1 line

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#192]
Fix case for SpaceCounter when we have 0 or 1 lines

1. If the file is empty (all code is commented)
2. If the file has 1 line (cause variance can be calculated for 2 points)

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#192` is not assigned, can't get performer
