### ISSUE TITLE
ThisFind patterns fails

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#194]
ThisFind patterns fails for the current files:
[ThisFindFiles.zip](https://github.com/yegor256/aibolit/files/4460888/ThisFindFiles.zip)

You can see the full log here:
[errors.txt](https://github.com/yegor256/aibolit/files/4460884/errors.txt)

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lyriccoder** [comment]
@0crat  assign to @lukyanoffpashok

**Comment by 0crat** [comment]
> @0crat assign to @lukyanoffpashok  ([here](https://github.com/yegor256/aibolit/issues/194#issuecomment-611956667))

@lyriccoder You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by acheshkov** [comment]
@0crat assign to @lukyanoffpashok

**Comment by acheshkov** [comment]
@lukyanoffpashok please take a look

**Comment by 0crat** [comment]
> @0crat assign to @lukyanoffpashok  ([here](https://github.com/yegor256/aibolit/issues/194#issuecomment-611959076))

@acheshkov There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 12@cf6a468ba0d0, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'to' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'to' of element 'performer' is not valid.
```

[0.53.1](https://github.com/zerocracy/farm): CID: [068c356b-c049-443f-92e5-03f3257ef65e](https://www.0crat.com/footprint/CT5UB7XAP/068c356b-c049-443f-92e5-03f3257ef65e), Type: "Start order"

**Comment by acheshkov** [comment]
@0crat reject

**Comment by 0crat** [comment]
> @0crat reject ([here](https://github.com/yegor256/aibolit/issues/194#issuecomment-611960336))

@acheshkov Job `gh:yegor256/aibolit#194` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#194](https://github.com/yegor256/aibolit/issues/194) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/dcf4780d-50ae-4154-b71d-d0d801d70298); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@lyriccoder I've made a PR with tests for this, and most of the cases don't trigger any error, please take a look

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@lyriccoder merged, please close

**Comment by paulodamaso** [comment]
@lyriccoder ping
