### ISSUE TITLE
Assert pattern fails for given files

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#195]
Assert pattern fails for given files
[AssertFiles.zip](https://github.com/yegor256/aibolit/files/4460942/AssertFiles.zip)

You can found full log here:
[errors.txt](https://github.com/yegor256/aibolit/files/4460946/errors.txt)

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat assign @tribals

**Comment by 0crat** [comment]
> @0crat assign @tribals  ([here](https://github.com/yegor256/aibolit/issues/195#issuecomment-611961831))

@acheshkov The job [#195](https://github.com/yegor256/aibolit/issues/195) assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/da8f4929-a22c-4076-b65e-8523234ad1f0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@tribals[/z](https://www.0crat.com/u/tribals) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @tribals[/z](https://www.0crat.com/u/tribals) resigned from [#195](https://github.com/yegor256/aibolit/issues/195), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#195](https://github.com/yegor256/aibolit/issues/195) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/d2ec1487-6129-49fe-8a24-be1b4b776c21); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@lyriccoder None of the files triggers error on `AssertInCode` pattern, please take a look at the draft

**Comment by lyriccoder** [comment]
it doesn't matter. 

1) We need to check empty cases
2) we had ~2000 errors when training a dataset, it means that we lost 2000 files

@acheshkov have you already fixed this patterns as i remember? Should we close this issue?

**Comment by paulodamaso** [comment]
@lyriccoder Is my PR valid then? Should I update its status?

**Comment by paulodamaso** [comment]
@acheshkov @lyriccoder ping
