### ISSUE TITLE
Metric: Count the number of leaves in an AST for each method

### ISSUE THREAD

**Issue by Vitaly-Protasov** [yegor256/aibolit#196]
As it was considered in #166 it's needed to add counting of leaf nodes in AST

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#196](https://github.com/yegor256/aibolit/issues/196) assigned to @vitaly-protasov[/z](https://www.0crat.com/u/vitaly-protasov), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/12c839f8-13df-4eb7-9552-abcedc4202f8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @vitaly-protasov[/z](https://www.0crat.com/u/vitaly-protasov) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by Vitaly-Protasov** [comment]
Soluted here: https://github.com/yegor256/aibolit/pull/198

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
