### ISSUE TITLE
deploy to pypi

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#2]

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by 0crat** [comment]
I'm not managing `yegor256/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
