### ISSUE TITLE
Implementing cognitive complexity by steps

### ISSUE THREAD

**Issue by lukyanoffpashok** [yegor256/aibolit#206]
https://github.com/yegor256/aibolit/issues/133 
We suggested to implement  considered metric step by step. In the first step lets consider incrementing only 'if, else if, for' structures without nesting.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by Vitaly-Protasov** [comment]
done

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#206` is not assigned, can't get performer
