### ISSUE TITLE
Consider nesting in cognitive complexity

### ISSUE THREAD

**Issue by Vitaly-Protasov** [yegor256/aibolit#212]
Main issue is #133 

The first step for solving cognitive complexity was at https://github.com/yegor256/aibolit/pull/207, but there was not considered nesting level for each structure; that's why this metric doesn't work correctly.

The next step is to add to the final value relying on the nesting level.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#212` is not assigned, can't get performer
