### ISSUE TITLE
Cognitive Complexity. Change policy of incrementing IfStatement

### ISSUE THREAD

**Issue by Vitaly-Protasov** [yegor256/aibolit#215]
Since the lash PR about Cognitive Complexity it was added incrementing for statements rely on their nesting level. 
But, as this metric was discussed in https://www.sonarsource.com/docs/CognitiveComplexity.pdf policy for inrementing IfStatement need to be changed.

For example, in structure 
![image](https://user-images.githubusercontent.com/43099602/79450232-58157780-7fed-11ea-9b4f-54d745e2c615.png) as you can notice, in 'else if' we didn't count it's nesting level, because we count it only in first 'if'

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#215](https://github.com/yegor256/aibolit/issues/215) assigned to @vitaly-protasov[/z](https://www.0crat.com/u/vitaly-protasov), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/7bc55a27-839b-4cf6-a56b-44199bdf00ea); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @vitaly-protasov[/z](https://www.0crat.com/u/vitaly-protasov) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@vitaly-protasov[/z](https://www.0crat.com/u/vitaly-protasov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by acheshkov** [comment]
@0crat pause

**Comment by 0crat** [comment]
> @0crat pause ([here](https://github.com/yegor256/aibolit/issues/215#issuecomment-617330097))

@acheshkov Can't understand "pause", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `elect` Trigger election for ticket
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0crat** [comment]
The user @vitaly-protasov[/z](https://www.0crat.com/u/vitaly-protasov) resigned from [#215](https://github.com/yegor256/aibolit/issues/215), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#215](https://github.com/yegor256/aibolit/issues/215) assigned to @tribals[/z](https://www.0crat.com/u/tribals), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/b7f61226-2bb5-4fab-8146-c9771b83443c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@tribals[/z](https://www.0crat.com/u/tribals) resigned from [#215](https://github.com/yegor256/aibolit/issues/215), since the job is not in scope anymore

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@470ff8ad-1642-4d34-9f48-355654d6ab84, thread: PQ-CT5UB7XAP
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [reason, priority, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.53.12](https://github.com/zerocracy/farm): CID: [1e603540-d740-49f2-8425-62d44ab470c6](https://www.0crat.com/footprint/CT5UB7XAP/1e603540-d740-49f2-8425-62d44ab470c6), Type: "Order was canceled"
