### ISSUE TITLE
Cognitive Complexity. Didn't consider logical operators

### ISSUE THREAD

**Issue by Vitaly-Protasov** [yegor256/aibolit#216]
At the last PR https://github.com/yegor256/aibolit/pull/213  javalang.tree.BinaryOperation was even commented. 
It's important to consider this operation, because it was mentioned in original article https://www.sonarsource.com/docs/CognitiveComplexity.pdf

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out  ([here](https://github.com/yegor256/aibolit/issues/216#issuecomment-614649655))

@acheshkov Job `gh:yegor256/aibolit#216` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#216` is not assigned, can't get performer
