### ISSUE TITLE
Cognitive complexity. It's important to add incrementing for recursion

### ISSUE THREAD

**Issue by Vitaly-Protasov** [yegor256/aibolit#219]
In original paper was discussed  about recursion:
![image](https://user-images.githubusercontent.com/43099602/79547184-3a531b80-809c-11ea-801f-87ec926b1cf9.png)

Hence, in this project this thing also need to be considered.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/219#issuecomment-615112159))

@acheshkov Job `gh:yegor256/aibolit#219` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#219` is not assigned, can't get performer
