### ISSUE TITLE
Need to calculate readability metrics

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#22]
The target class of our model is `Readability` class. It includes the numeric value from 0 up to 1 and tells us how well-readable the code is. 

At the moment, we do not have lots of reviewers to review all Java files. 
It is necessary to do the script which runs JAR (see the reference below) which estimates `Readability`. It is the result of the following paper :
> https://doi.org/10.1002/smr.1958

The reference of the paper is the following:

TY  - JOUR
AU  - Scalabrino, Simone
AU  - Linares-Vásquez, Mario
AU  - Oliveto, Rocco
AU  - Poshyvanyk, Denys
C7  - e1958
C8  - smr.1958
TI  - A comprehensive model for code readability
JO  - Journal of Software: Evolution and Process
JA  - J Softw Evol Proc
VL  - 30
IS  - 6
SN  - 2047-7473
UR  - https://doi.org/10.1002/smr.1958
DO  - doi:10.1002/smr.1958
SP  - e1958
KW  - code readability
KW  - quality warning prediction
KW  - textual analysis
PY  - 2018
AB  - Abstract Unreadable code could compromise program comprehension, and it could cause the introduction of bugs. Code consists of mostly natural language text, both in identifiers and comments, and it is a particular form of text. Nevertheless, the models proposed to estimate code readability take into account only structural aspects and visual nuances of source code, such as line length and alignment of characters. In this paper, we extend our previous work in which we use textual features to improve code readability models. We introduce 2 new textual features, and we reassess the readability prediction power of readability models on more than 600 code snippets manually evaluated, in terms of readability, by 5K+ people. We also replicate a study by Buse and Weimer on the correlation between readability and FindBugs warnings, evaluating different models on 20 software systems, for a total of 3M lines of code. The results demonstrate that (1) textual features complement other features and (2) a model containing all the features achieves a significantly higher accuracy as compared with all the other state-of-the-art models. Also, readability estimation resulting from a more accurate model, ie, the combined model, is able to predict more accurately FindBugs warnings.
ER  -

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT5UB7XAP) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#22` is not assigned, can't get performer
