### ISSUE TITLE
Fix metric CountLeaves in AST for each method

### ISSUE THREAD

**Issue by Vitaly-Protasov** [yegor256/aibolit#221]
In https://github.com/yegor256/aibolit/blob/master/aibolit/metrics/countLeaves/numberofleaves.py
there's some problem. 

The purpose of this metric is to count number of leaves for each class's method, but it doesn't work properly. In function 
`   

     def value(self, filename: str):

        tree = JavalangImproved(filename)

        nodes = tree.tree_to_nodes()
        traversed = []
        for each_node in nodes:
            if type(each_node.node) == javalang.tree.MethodDeclaration:
                traversed.append(countLeaves(each_node.node.body))

        return sum(traversed)`

handles each MethodDeclaration in AST, hence it also works with nested methodDeclaration which give us extra leaves. It must be fixed

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#221` is not assigned, can't get performer
