### ISSUE TITLE
Metric LCOM4: does not work with subclasses

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#225]
#### For now, the algorithm only works fine in java classes:

- with no abstract classes containing shadowing methods. 

_Originally posted by @silverCase in https://github.com/yegor256/aibolit/pull/218#issuecomment-615344836_

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out  ([here](https://github.com/yegor256/aibolit/issues/225#issuecomment-615347924))

@acheshkov Job `gh:yegor256/aibolit#225` is not assigned, can't get performer

**Comment by silverCase** [comment]
The line `with no subclasses.`
Please change it to  `with no abstract classes containing shadowing methods.`

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
The job [#225](https://github.com/yegor256/aibolit/issues/225) assigned to @silvercase[/z](https://www.0crat.com/u/silvercase), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/d1a96bfc-8567-49ea-9287-50777d144736); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @silvercase[/z](https://www.0crat.com/u/silvercase) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/225#issuecomment-620620720))

@acheshkov GitHub issue is still open, won't close

**Comment by 0crat** [comment]
@silvercase[/z](https://www.0crat.com/u/silvercase) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by acheshkov** [comment]
@0crat pause

**Comment by 0crat** [comment]
> @0crat pause ([here](https://github.com/yegor256/aibolit/issues/225#issuecomment-623855860))

@acheshkov Can't understand "pause", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `elect` Trigger election for ticket
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by acheshkov** [comment]
@0crat wait
