### ISSUE TITLE
Metric LCOM4: attribute name shadowing does not work

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#226]
#### For now, the algorithm only works fine in java classes:

- with no attribute name shadowing 

_Originally posted by @silverCase in https://github.com/yegor256/aibolit/pull/218#issuecomment-615344836_

**Comment by 0crat** [comment]
The job [#226](https://github.com/yegor256/aibolit/issues/226) assigned to @silvercase[/z](https://www.0crat.com/u/silvercase), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/3dc72afa-d511-4c62-b8ae-76deabbf1cc9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @silvercase[/z](https://www.0crat.com/u/silvercase) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@silvercase[/z](https://www.0crat.com/u/silvercase) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @silvercase[/z](https://www.0crat.com/u/silvercase) resigned from [#226](https://github.com/yegor256/aibolit/issues/226), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/226#issuecomment-629623647))

@acheshkov Job `gh:yegor256/aibolit#226` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#226` is not assigned, can't get performer
