### ISSUE TITLE
Add intergration test

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#228]
Test patterns and metrics on the subset of Java classes. Test checks that calculation of patterns and metrics do not throw the error.

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/228#issuecomment-616419255))

@acheshkov Job `gh:yegor256/aibolit#228` is not assigned, can't get performer

**Comment by acheshkov** [comment]
#232

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#228` is not assigned, can't get performer
