### ISSUE TITLE
Need to calculate Halstead Metrics

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#23]
Often, Halstead metrics are used to measure readability code as it is demonstrated in the following paper:

Daryl Posnett, Abram Hindle, and Premkumar Devanbu. 2011. A simpler model of software readability. In Proceedings of the 8th Working Conference on Mining Software Repositories (MSR ’11). Association for Computing Machinery, New York, NY, USA, 73–82. DOI:https://doi.org/10.1145/1985441.1985454

We need to calculate at least `Volume` with the following program (or find a similar program):

https://github.com/aametwally/Halstead-Complexity-Measures

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT5UB7XAP) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by zuoqin** [comment]
@yegor256, Halstead Metric is calculated using complecated algorithms build above eclipse Java packages, which is impossible to implement in Python. How to add it to this repository?

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#23` is not assigned, can't get performer
