### ISSUE TITLE
Need to get rid of NN model

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#246]
At the moment we are using `torch` and NN model. We need to replace it with the new `Two fold` model

**Comment by lyriccoder** [comment]
I will implement it

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lyriccoder** [comment]
@0crat  assign to @lyriccoder

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dc9a75c2-99a9-40a1-bc27-ddaf8f08c10c, thread: pool-667-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.12](https://github.com/zerocracy/farm): Issue: yegor256/aibolit#246, Comment: 619867766

**Comment by 0crat** [comment]
The job [#246](https://github.com/yegor256/aibolit/issues/246) assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/d1ccaf07-9536-49e8-930a-6d276c9bdb9d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/246#issuecomment-622950032))

@acheshkov GitHub issue is still open, won't close

**Comment by acheshkov** [comment]
@0crat wait
