### ISSUE TITLE
Documentation, typing and refactoring for LCOM4 PR

### ISSUE THREAD

**Issue by silverCase** [yegor256/aibolit#251]
#231

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/251#issuecomment-620614475))

@acheshkov Job `gh:yegor256/aibolit#251` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#251](https://github.com/yegor256/aibolit/issues/251) assigned to @silvercase[/z](https://www.0crat.com/u/silvercase), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/adf87fd5-dc71-45e7-9fbe-d42f6e830574); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @silvercase[/z](https://www.0crat.com/u/silvercase) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/251#issuecomment-620614475))

@acheshkov @silvercase[/z](https://www.0crat.com/u/silvercase) resigned from [#251](https://github.com/yegor256/aibolit/issues/251), since the job is not in scope anymore

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/251#issuecomment-620614475))

@acheshkov There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6d493ca1-e1fd-4f5c-9139-8d69db279e5e, thread: PQ-CT5UB7XAP
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [issue, repo, comment, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.53.13](https://github.com/zerocracy/farm): CID: [422bb2f9-b26a-419e-a72b-c3dba38dc33e](https://www.0crat.com/footprint/CT5UB7XAP/422bb2f9-b26a-419e-a72b-c3dba38dc33e), Type: "Order was canceled"

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#251` is not assigned, can't get performer
