### ISSUE TITLE
ML pipeline; Custom folder of JAVA files

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#252]
1. Able to use for training custom folder 
2. custom folder defined using  environment variable "JAVA_FILES_PATH"
3. If JAVA_FILES_PATH is not defined use old behavior

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/252#issuecomment-620847873))

@acheshkov Job `gh:yegor256/aibolit#252` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#252` is not assigned, can't get performer
