### ISSUE TITLE
Create Docker image with JAVA classes dataset and other jar's

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#256]

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out  ([here](https://github.com/yegor256/aibolit/issues/256#issuecomment-621920100))

@acheshkov GitHub issue is still open, won't close

**Comment by 0crat** [comment]
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @acheshkov[/z](https://www.0crat.com/u/acheshkov) (its creator); I won't close the order; please, re-open it and ask @acheshkov[/z](https://www.0crat.com/u/acheshkov) to close it

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) resigned from [#256](https://github.com/yegor256/aibolit/issues/256), since the job is not in scope anymore

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@da945c9f-54c4-44f9-95c4-928185ec3345, thread: PQ-CT5UB7XAP
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [reason, priority, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.53.14](https://github.com/zerocracy/farm): CID: [6eb570de-8249-4f35-b0ef-6ec90bac4c12](https://www.0crat.com/footprint/CT5UB7XAP/6eb570de-8249-4f35-b0ef-6ec90bac4c12), Type: "Order was canceled"
