### ISSUE TITLE
Design recommendation sensitivity threshold

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#258]
The sensitivity is a number in range `[0, 1]`. Where `1` means inform about all potential issues, and `0` means ignore all recommendations.

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
The job [#258](https://github.com/yegor256/aibolit/issues/258) assigned to @acheshkov[/z](https://www.0crat.com/u/acheshkov), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/06db1d98-6940-4c93-bf2c-3b32d30e63b8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @acheshkov[/z](https://www.0crat.com/u/acheshkov) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/258#issuecomment-622323362))

@acheshkov GitHub issue is still open, won't close

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
