### ISSUE TITLE
Create parameter for threshold (recommend pipeline)

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#264]

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#264` is not assigned, can't get performer
