### ISSUE TITLE
Joined validation pattern completely fails and raises exceptions

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#265]
There are about 1436 errors for `joined validation` pattern. 

1) Fix them all.

Here is the script with the list of files
[temp.py.txt](https://github.com/yegor256/aibolit/files/4586321/temp.py.txt)

Here are all files:
[files.tar.gz](https://github.com/yegor256/aibolit/files/4586331/files.tar.gz)

2) add java classes to the list which is tested by `all.py`. Each class with unique  type of exception must be added:

```
'DoStatement' object has no attribute 'statements',
'ReturnStatement' object has no attribute 'statements',
'StatementExpression' object has no attribute 'statements',
'BreakStatement' object has no attribute 'statements',
'ForStatement' object has no attribute 'statements',
'IfStatement' object has no attribute 'statements',
'SwitchStatement' object has no attribute 'statements',
'ContinueStatement' object has no attribute 'statements'
```

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by acheshkov** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/yegor256/aibolit/issues/265#issuecomment-624698188))

@acheshkov The job [#265](https://github.com/yegor256/aibolit/issues/265) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/720fa350-d27d-4354-bcc4-ee83db6335fe); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@lyriccoder I've fixed the errors, but I couldn't understand the second part ("add java classes to the list which is tested by all.py"); am I supposed to add tests for each of these cases in our sample classes?

**Comment by lyriccoder** [comment]
there are integration tests, they a relocated here:
https://github.com/yegor256/aibolit/tree/master/test/integration
1) you need to uncomment `p23` pattern

`EXCLUDE_PATTERNS = ['P23']` must be replaced with `EXCLUDE_PATTERNS = []`
2) 

> am I supposed to add tests for each of these cases in our sample classes?

yes, you need to add classes to the following folder for each of mentioned cases:
https://github.com/yegor256/aibolit/tree/master/test/integration/samples

Then you will need to run `python all.py` to check whether all tests are passed

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@lyriccoder ping
