### ISSUE TITLE
This finder pattern has errors

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#269]
This finder,'StatementExpression' object has no attribute 'statements'
'IfStatement' object has no attribute 'statements',
'Statement' object has no attribute 'statements'

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#269` is not assigned, can't get performer
