### ISSUE TITLE
1.0.0a1

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#278]
Alpha release

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
The job [#278](https://github.com/yegor256/aibolit/issues/278) assigned to @acheshkov[/z](https://www.0crat.com/u/acheshkov), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/265a8900-a509-48de-a0fa-232a195f9c2d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @acheshkov[/z](https://www.0crat.com/u/acheshkov) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/278#issuecomment-626495533))

@acheshkov Job [#278](https://github.com/yegor256/aibolit/issues/278) is not in the agenda of @acheshkov[/z](https://www.0crat.com/u/acheshkov), can't set title

**Comment by acheshkov** [comment]
@rultor release tag is 1.0.0a1

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/278#issuecomment-626495533))

@acheshkov GitHub issue is still open, won't close

**Comment by acheshkov** [comment]
@rultor release, tag=`1.0.0a1`

**Comment by 0crat** [comment]
Job was finished in 12 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
