### ISSUE TITLE
method_siblings.py:30-32: Implement method_siblings...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/aibolit#281]
The puzzle `142-80952438` from #142 has to be resolved: 

https://github.com/yegor256/aibolit/blob/76b6e4ebc5fa3260b3c44acd53e640d098107f64/aibolit/patterns/method_siblings/method_siblings.py#L30-L32

The puzzle was created by paulodamaso on 26-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat in

**Comment by acheshkov** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/yegor256/aibolit/issues/281#issuecomment-629868944))

@acheshkov The job [#281](https://github.com/yegor256/aibolit/issues/281) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/3e17471e-1b45-4bf6-b403-c33ce6e9e914); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/yegor256/aibolit/pull/347

**Comment by 0pdd** [comment]
The puzzle `142-80952438` has disappeared from the source code, that's why I closed this issue.
