### ISSUE TITLE
var_siblings.py:7-9: Implement var_siblings pattern. This...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/aibolit#284]
The puzzle `141-6e9388cb` from #141 has to be resolved: 

https://github.com/yegor256/aibolit/blob/76b6e4ebc5fa3260b3c44acd53e640d098107f64/aibolit/patterns/var_siblings/var_siblings.py#L7-L9

The puzzle was created by paulodamaso on 26-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat in

**Comment by acheshkov** [comment]
@0crat assign @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/yegor256/aibolit/issues/284#issuecomment-629868818))

@acheshkov The job [#284](https://github.com/yegor256/aibolit/issues/284) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/141e70fa-942b-44b8-a9ad-0e56ba641ee1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/yegor256/aibolit/pull/346

**Comment by 0pdd** [comment]
The puzzle `141-6e9388cb` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#749](https://github.com/cqfn/aibolit/issues/749) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#749](https://github.com/cqfn/aibolit/issues/749) is solved here.
