### ISSUE TITLE
Implement new feature in Aibolit

### ISSUE THREAD

**Issue by angusev** [yegor256/aibolit#289]
Make possible to obtain pattern and metrics of input java classes with a special flag.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You @angusev[/z](https://www.0crat.com/u/angusev) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/289#issuecomment-628100101))

@acheshkov Job `gh:yegor256/aibolit#289` is not assigned, can't get performer

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#289` is not assigned, can't get performer
