### ISSUE TITLE
Update documentation for aibolit (recommend)

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#298]
Update documentation for aibolit (recommend)

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`
