### ISSUE TITLE
Release 1.0.0-alpha2

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#301]

**Comment by acheshkov** [comment]
@0crat out

**Comment by acheshkov** [comment]
@rultor release, tag=1.0.0a2

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@47be01ee-43c3-4083-893b-28d1d64d4ea7, thread: pool-2267-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.14](https://github.com/zerocracy/farm): Issue: yegor256/aibolit#301, Comment: 628586441

**Comment by acheshkov** [comment]
@rultor release, tag=`1.0.0a2`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#301` is not assigned, can't get performer
