### ISSUE TITLE
VarSiblings is empty. It has empty value() method

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#306]
VarSiblings is empty. It has empty `value()` method

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@lyriccoder Is this issue duplicate of #284 ?

**Comment by lyriccoder** [comment]
now I see, yes, it's true. By some reason the bot which creates issues with #todo now is working

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#306` is not assigned, can't get performer
