### ISSUE TITLE
01-fetch-github.py must accept the max amount of repos

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#31]
I should be able to run:

```
$ python 01-fetch-github.py --repos=10
```

And it will fetch exactly 10 repositories. If I say `--repos=1` it will fetch just one.

**Comment by yegor256** [comment]
@zuoqin please, take care of this one

**Comment by yegor256** [comment]
@zuoqin thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#31` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
