### ISSUE TITLE
Create parameter which will allow to skip dataset collection

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#315]
At the moment we first collect dataset (calculate metrics,patterns) and then we train a model.
Need to skip dataset collection since it takes too much time. So, if we have already a dataset, we need to skip this procedure
We can set it via `HOME_DATASET_CSV` env variable

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#315` is not assigned, can't get performer
