### ISSUE TITLE
New release with new model

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#316]
We need to make a new release with new model. New model will have target: Cognitive complexity. Also, some patterns will be added to a new dataset

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/316#issuecomment-629803247))

@acheshkov Job `gh:yegor256/aibolit#316` is not assigned, can't get performer

**Comment by acheshkov** [comment]
@rultor release, tag=`1.0.0`

**Comment by acheshkov** [comment]
@lyriccoder, @yegor256  congrats us!

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#316` is not assigned, can't get performer
