### ISSUE TITLE
Change project description setup.py

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#318]
`DevTool recommending how to improve the maintenance quality of your Java classes.`

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/318#issuecomment-629824278))

@acheshkov Job `gh:yegor256/aibolit#318` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#318` is not assigned, can't get performer
