### ISSUE TITLE
Make an option to make full report for aibolit

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#320]

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/320#issuecomment-630395957))

@acheshkov Job `gh:yegor256/aibolit#320` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#320` is not assigned, can't get performer
