### ISSUE TITLE
Aibolit have lot of logs

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#322]
AT the moment Catboost  creates lots of unnecessary logs. They have to remove it every time the program is run

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#322` is not assigned, can't get performer
