### ISSUE TITLE
--full instead of --full_report

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#323]
Please, rename command line option `--full_report` to `--full`. Thanks.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#323` is not assigned, can't get performer
