### ISSUE TITLE
Detect encoding

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#324]
Detect encoding in each pattern. At the moment we use only utf-8 by default. Chinese symbols cannot be parsed

We need to detect encoding via cchardet.
Also, NullAssignment is not using encoding at all. Find similar patterns

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`
