### ISSUE TITLE
max_classes parameter does not work for multiprocessing (02-filter-and-move.py)

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#337]

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#337` is not assigned, can't get performer
