### ISSUE TITLE
P21 Var in the middle is wrong about my code

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#340]
This is Java code I have:

```java
    public void returnsIteratorWithSupportedRemove() {
        final CollectionEnvelope<String> list = new CollectionEnvelope<String>(
            new CollectionOf<>("eleven")
        ) {
        };
        final Iterator<String> iterator = list.iterator();
        iterator.next();
        iterator.remove();
        new Assertion<>(
            "Must return an empty Iterator",
            new IterableOf<>(iterator),
            new IsEmptyIterable<>()
        ).affirm();
    }
```

P21 says that line 6 has "var in the middle". It seems that it's a mistake. The `iterator` variable is _not_ in the middle.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You @aravij[/z](https://www.0crat.com/u/aravij) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#340` is not assigned, can't get performer
