### ISSUE TITLE
The <output_string> is not consistent

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#341]
The `<output_string/>` element is present only for files with not patterns. This, I believe, is not correct. It should either be everywhere or nowhere.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#341` is not assigned, can't get performer
