### ISSUE TITLE
It's not clear where to find output report

### ISSUE THREAD

**Issue by g4s8** [yegor256/aibolit#351]
When I run `aibolit` tool for the first time, I thought my code doesn't have any problems, but then I read documentation more accurately, and found that the report was saved to the `out.xml` file. But I expected it to be printed to system output (before reading it). It's hard to find in documentation, because it appears after technical details of CLI tool implementation which I not really needed to run it:

Now it looks like:
> # Recommend command
> CLI usage (important for user)
> Some technical details about model and patterns (important for contributors)
> The output of recommendation will be saved to the out.xml (important for user)

I'd suggest writing report location to the console output at the end of `recommend` command run:
```
Analyzing src/main/java/com/artipie/http/rq/Part.java
Analyzing src/main/java/com/artipie/http/rq/package-info.java
Analyzing src/main/java/com/artipie/http/rq/Multipart.java
...
Analyzing src/main/java/com/artipie/http/Response.java

Aibolit report saved to out.xml
```

And move `out.xml` reference in README file a bit up to put it before technical details.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lyriccoder** [comment]
duplicate for #338

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#351` is not assigned, can't get performer
