### ISSUE TITLE
Convert out.xml to human-readable format

### ISSUE THREAD

**Issue by g4s8** [yegor256/aibolit#352]
It's good to have XML report for `recommend` command (e.g. for CI tools or other dev tools), but it's hard to read for developer. I'd suggest making an option to render this report as a plain text or introduce additional command to parse report from XML to human-readable format. It may look like:
```
./src/main/java/SomeClass.java
 - line22: P20_5: Line distance between variable declaration and first usage greater then threshold.
 If line distance between variable declaration and first usage exceeds some threshold we consider it as the pattern. 
 - line 34: Class constructor except this contains other code.
 The first constructor has this() and some other statements. This is the "hybrid constructor" pattern.
```

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/352#issuecomment-634003421))

@acheshkov Job `gh:yegor256/aibolit#352` is not assigned, can't get performer

**Comment by acheshkov** [comment]
@g4s8 try the version `1.0.3` it has text output option

```
$ pip install aibolit -U
```

```bash
$ aibolit recommend --folder src/java --format=text --full
```

**Comment by g4s8** [comment]
@acheshkov thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#352` is not assigned, can't get performer
