### ISSUE TITLE
Rename --filenames to --files

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#355]
Try to stay away from compound names as much as you can. Just `--files` is descriptive enough.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by yegor256** [comment]
see #363

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#355` is not assigned, can't get performer
