### ISSUE TITLE
Non final attribute (P12) must ignore static constants in interfaces

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#357]
This is the example:

```
interface Foo {
  int BAR = 1;
}
```

This `BAR` is OK, there is no pattern here.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lyriccoder** [comment]
@0crat assign to @paulodamaso

**Comment by 0crat** [comment]
> @0crat assign to @paulodamaso  ([here](https://github.com/yegor256/aibolit/issues/357#issuecomment-635188446))

@lyriccoder You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by lyriccoder** [comment]
@paulodamaso could you please assign it to yourself? seems it's your pattern

**Comment by paulodamaso** [comment]
@lyriccoder I don't think I have the permissions for that.

**Comment by paulodamaso** [comment]
@acheshkov Could you please assign me?

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by paulodamaso** [comment]
@0crat wait for #403 merge

**Comment by 0crat** [comment]
> @0crat wait for #403 merge ([here](https://github.com/yegor256/aibolit/issues/357#issuecomment-644952165))

@paulodamaso Job `gh:yegor256/aibolit#357` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#357` is not assigned, can't get performer

**Comment by acheshkov** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/aibolit/issues/357#issuecomment-647762496))

@acheshkov Job `gh:yegor256/aibolit#357` is not assigned, can't get performer
