### ISSUE TITLE
"some issues found" is redundant message in the log

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#358]
There is no point to print this line in the `long` log: 

```
/code/takes/src/main/java/org/takes/rq/RqMethod.java: some issues found
/code/takes/src/main/java/org/takes/rq/RqWithBody.java: your code is perfect in aibolit's opinion
```

Please, remove them. Both lines are unnecessary.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lyriccoder** [comment]
In this case how can we differ the cases when there is no issues and smth is found? otherwise a user will ask for a file: "why was it missed?"

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#358` is not assigned, can't get performer
