### ISSUE TITLE
ignore package-info.java files

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#359]
We should not check `package-info.java` files:

```
/code/takes/src/main/java/org/takes/rq/package-info.java: your code is perfect in aibolit's opinion
```

This is wrong.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#359` is not assigned, can't get performer
