### ISSUE TITLE
Print the score of the pattern and the total number of patterns

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#360]
This is what I see in the log now:

```
RequestOf.java[94]: Null check (P13)
```

I would like to see this instead:

```
RequestOf.java[94]: Null check (P13: 5.65 2/13)
```

Here: 

  * 5.65 is the score of this pattern
  * 2 is the position of this pattern in the total list of patterns found in the file
  * 13 is the total number of found patterns

These numbers should also be visible in the XML.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#360` is not assigned, can't get performer
