### ISSUE TITLE
P21 var in the middle is wrong for variable declaration

### ISSUE THREAD

**Issue by g4s8** [yegor256/aibolit#365]
I have this code:
```java
149:                     last -> {
150:                            final Optional<Long> size;
151:                            if (last >= S3Storage.MIN_MULTIPART) {
152:                                size = Optional.empty();
153:                            } else {
154:                                size = Optional.of(last);
155:                            }
156:                            return size;
157:                      }
```
The variable `size` defined at line `150` but assigned conditionally at line `152` or `154`.
The report of `aibolit` says that `line 150: Var in the middle (P21)`, but actually this variable can't be assessed before `155` line with initialization in `152` or `154`.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by g4s8** [comment]
@lyriccoder @acheshkov it seems this ticket was closed by mistake: PR #367 was addressed #364 issue, not #365

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#365` is not assigned, can't get performer

**Comment by acheshkov** [comment]
@g4s8 could you provide a full listing of the function with this code? Var in the middle considered as a violation if the variable declared in the middle of the current visibility scope.

**Comment by g4s8** [comment]
@acheshkov updated: please check the question

**Comment by lyriccoder** [comment]
Got it, seems you do not consider a new scope as a lambda function. You need to check the place where you describe new scopes

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You @aravij[/z](https://www.0crat.com/u/aravij) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by aravij** [comment]
@g4s8 Thanks for snippet, but can you add or link a minimal working example next time. Just to mention, I turned your snippet in the following test data and it will not produce P21 error.
```java
import java.util.function.Function;
import java.util.Optional;

public class Test {
    private ArrayList<Long> array;

    public void setArray(ArrayList<Long> newArray) {
        array = newArray;
    }

    public ArrayList<Long> filterWithOptionalEmpty(Long threshold) {
        Function<Long, Long> filter = last -> {
            final Optional<Long> size;
            if (last >= threshold) {
                size = Optional.empty();
            } else {
                size = Optional.of(last);
            }
            return size;
        };

        return array.map(filter);
    }
}

```

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#365` is not assigned, can't get performer
