### ISSUE TITLE
rename "recommend" to "check"

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#368]
It would be more logical call it like this:

```
$ aibolit check
```

This is the terminology all other static analyzers are using: _checking_ the code to find issues.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#368` is not assigned, can't get performer
