### ISSUE TITLE
--suppress

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#372]
Would be great to have an ability to suppress certain patterns:

```
$ aibolit recommend --suppress=P10,P21 test.java
```

These patterns will be ignored.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by lyriccoder** [comment]
as discussed with @yegor256, we will make suppressed pattern be equal to 0.
Since we do not care about some certain patterns, we must exclude it from the prediction. It can affect the importance of different patterns

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#372` is not assigned, can't get performer
