### ISSUE TITLE
--weight

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#373]
Let's make it possible to define the weight for certain patterns in the final calculation:

```
$ aibolit recommend --weight=P10:0.5 --weight=P21:1.5
```

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lyriccoder** [comment]
@yegor256, @acheshkov  and me thinks that we do not need to define the weight for certain patterns in the final calculation. In this case it's manual weights and we do not need ML here. It's brown magic.
@acheshkov could you please confirm?

**Comment by acheshkov** [comment]
@lyriccoder I confirm

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#373` is not assigned, can't get performer
