### ISSUE TITLE
Patterns dictionary. Change pattern's order 

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#376]
Sort patterns in the PATTERN.md ascending by lexicographical order: P1, P2, ....

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#376` is not assigned, can't get performer
