### ISSUE TITLE
Add verions of aibolit, datetime to xml report

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#383]
```
	<header>
		<datetime>37245872159827</datetime>
		<version>1.0.2</version>
		<cmd>aibolit recommend --filenames UserServiceImpl.java --full</cmd>
		<total_maintainability_score>68.8228119497855</total_maintainability_score> <!-- May be here or at the current place, I'm OK -->
	</header>
```

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#383` is not assigned, can't get performer
