### ISSUE TITLE
Add/fix explanation of total score to Readme.pd 

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#385]
1) need to explain how 18.3 score differs from 2.8
2) need to add information about how to know that patterns should be fixed first

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#385` is not assigned, can't get performer
