### ISSUE TITLE
AST class refactoring.

### ISSUE THREAD

**Issue by aravij** [yegor256/aibolit#390]
AST class needs to be splitted into two separate modules for file encoding detection and ast building.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You @aravij[/z](https://www.0crat.com/u/aravij) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#390` is not assigned, can't get performer
