### ISSUE TITLE
prepare config for new release

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#401]
Need to remove duplicates in config
Need to add new metrics implemented by @Vitaly-Protasov

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#401` is not assigned, can't get performer
