### ISSUE TITLE
Make new release 1.1.0

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#407]

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) are: `REV`

**Comment by lyriccoder** [comment]
1) Complexity is predicted as a negative value. Should we use it?
2) if yes, then if we have 2 negative value -2 real CC, -10 after pattern change, then the diff is -2-(-10)=-8. Since we usually we do the following ( to understand whether it is increased or decreased): diff * -1, we will get +8, but actually complexity decreased
3) we have too small score (usually, it is not more than 0.2). That's why the average score is really small
4) As soon we have more, than 1 value, the patterns become to have 0 importance (diff=0)

**Comment by acheshkov** [comment]
@0crat out

**Comment by acheshkov** [comment]
> 1. Complexity is predicted as a negative value. Should we use it?

It's strange, as I sad

**Comment by acheshkov** [comment]
> 3\. we have too small score (usually, it is not more than 0.2). That's why the average score is really small

how we calculate patterns' importance now?

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#407` is not assigned, can't get performer
