### ISSUE TITLE
Modify instance_of

### ISSUE THREAD

**Issue by lukyanoffpashok** [yegor256/aibolit#413]

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@abb255a1-bcf3-4f3a-b309-45c684d4eb9c, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Evaluate pattern on arbitary AST' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [0ea2a856-828e-44dc-8f98-5f104bc55e81](https://www.0crat.com/footprint/CT5UB7XAP/0ea2a856-828e-44dc-8f98-5f104bc55e81), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#413` is not assigned, can't get performer
