### ISSUE TITLE
Create classes representing Java classes, methods and fields.

### ISSUE THREAD

**Issue by aravij** [yegor256/aibolit#414]
To operate on a source code we need to represent its parts as packages, classes, methods and fields by separate objects with its own functionality.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @aravij[/z](https://www.0crat.com/u/aravij) are: `DEV`, `REV`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@abb255a1-bcf3-4f3a-b309-45c684d4eb9c, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Evaluate pattern on arbitary AST' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [5faff3c0-8e5c-485b-9bcb-0aa21f7ed8ad](https://www.0crat.com/footprint/CT5UB7XAP/5faff3c0-8e5c-485b-9bcb-0aa21f7ed8ad), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#414` is not assigned, can't get performer
