### ISSUE TITLE
Class methods and fields usage

### ISSUE THREAD

**Issue by aravij** [yegor256/aibolit#419]
Create new methods to find out which fields and methods are used in any given class method.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@54bbf007-af81-47f4-889b-85871a7a9b4d, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Evaluate pattern on arbitary AST' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [4de353fd-c470-4bed-9f4b-dcf372bcaeaa](https://www.0crat.com/footprint/CT5UB7XAP/4de353fd-c470-4bed-9f4b-dcf372bcaeaa), Type: "Job milestoned"

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @aravij[/z](https://www.0crat.com/u/aravij) are: `DEV`, `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#419` is not assigned, can't get performer
