### ISSUE TITLE
Var in the middle (P21) false positive

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#425]
This is my Java code:

```java
private static StringBuilder fakeBody(final Request... parts)
        throws IOException {
        final StringBuilder builder = new StringBuilder();
        for (final Request part : parts) {
            builder.append(String.format("--%s", RqMtFake.BOUNDARY))
                .append(RqMtFake.CRLF)
                .append("Content-Disposition: ")
                .append(
                    new RqHeaders.Smart(
                        new RqHeaders.Base(part)
                    ).single("Content-Disposition")
                ).append(RqMtFake.CRLF);
            final String body = new RqPrint(part).printBody();
            if (!(RqMtFake.CRLF.equals(body) || body.isEmpty())) {
                builder.append(RqMtFake.CRLF)
                    .append(body)
                    .append(RqMtFake.CRLF);
            }
        }
        builder.append("Content-Transfer-Encoding: utf-8")
            .append(RqMtFake.CRLF)
            .append(String.format("--%s--", RqMtFake.BOUNDARY));
        return builder;
    }
```

It points me to the second line and says that variable `builder` is "in the middle".

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by aravij** [comment]
@yegor256 Can you please provide minimal working example? Currently you code can't be parsed. I have put it in a class. Now it pass parsing, but I don't get error for `builder` variable. Only for `body` inside `for` cycle.

**Comment by yegor256** [comment]
@aravij try this class: https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/rq/multipart/RqMtFake.java

**Comment by aravij** [comment]
The problem was in annotation with params. It is now fixed. If you have some other positive false examples, it might be better to submit it here and fix in the same PR.

**Comment by yegor256** [comment]
@yegor256 I will make other tickets, if I find something else. Let's release this one.

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#425` is not assigned, can't get performer
