### ISSUE TITLE
Implement metric:  Response For Class (RFC)

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#436]
https://www.oreilly.com/library/view/sonar-code-quality/9781849517867/ch09s04.html#:~:text=your%20free%20trial-,The%20Response%20for%20Class%20metric,directly%20within%20the%20class%20methods.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@29809562-733e-4e81-93e4-bb6778714188, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Aibolit (multi-target)' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [d2109876-5d3a-4100-948a-3ed683f8f554](https://www.0crat.com/footprint/CT5UB7XAP/d2109876-5d3a-4100-948a-3ed683f8f554), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#436` is not assigned, can't get performer
