### ISSUE TITLE
Implement metric: LCOM5

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#437]

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@29809562-733e-4e81-93e4-bb6778714188, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Aibolit (multi-target)' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [0c9b0d95-72bb-4ae9-b016-18b1d14f198b](https://www.0crat.com/footprint/CT5UB7XAP/0c9b0d95-72bb-4ae9-b016-18b1d14f198b), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#437` is not assigned, can't get performer
