### ISSUE TITLE
Get used fields of method.

### ISSUE THREAD

**Issue by aravij** [yegor256/aibolit#439]
Functionality to get all used class fields ASTs for given method.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@592e6706-44da-4634-a6e2-8ab630bff16f, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Evaluate pattern on arbitary AST' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [0e88a6d7-eb32-49ce-b64e-d775af4fbb7e](https://www.0crat.com/footprint/CT5UB7XAP/0e88a6d7-eb32-49ce-b64e-d775af4fbb7e), Type: "Job milestoned"

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @aravij[/z](https://www.0crat.com/u/aravij) are: `DEV`, `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#439` is not assigned, can't get performer
