### ISSUE TITLE
Fix TwoFoldRankingModel (quantity func) 

### ISSUE THREAD

**Issue by angusev** [yegor256/aibolit#440]
1. Recommendation method must not take into account quantity function (logarithm default) 
https://github.com/yegor256/aibolit/blob/6c139802a3e914c825cc14039a8309095faa712b/aibolit/model/model.py#L150

2. Rewrite `informative` method [2] to make clear that it takes only one snippet as input

https://github.com/yegor256/aibolit/blob/6c139802a3e914c825cc14039a8309095faa712b/aibolit/model/model.py#L192

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#440` is not assigned, can't get performer
