### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by angusev** [yegor256/aibolit#445]
1. I think renaming (X -> snippet, X_old -> patterns_orig) will sufficiently enhance readability.
https://github.com/yegor256/aibolit/blob/5bc30f6e158c42652b7e2eca4f6e01c9e6bc2270/aibolit/model/model.py#L171

2. Make `sigmoid` method a `staticmethod`.
https://github.com/yegor256/aibolit/blob/5bc30f6e158c42652b7e2eca4f6e01c9e6bc2270/aibolit/model/model.py#L102

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by lyriccoder** [comment]
fixed in https://github.com/yegor256/aibolit/pull/444

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#445` is not assigned, can't get performer
