### ISSUE TITLE
Modify_string_concat

### ISSUE THREAD

**Issue by lukyanoffpashok** [yegor256/aibolit#446]

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@7c2626e2-2029-482d-b544-fb15f716f30d, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Evaluate pattern on arbitary AST' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [648b9f66-95b2-48f7-aa18-86a15582fc1b](https://www.0crat.com/footprint/CT5UB7XAP/648b9f66-95b2-48f7-aa18-86a15582fc1b), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#446` is not assigned, can't get performer
