### ISSUE TITLE
Modify multiple_while

### ISSUE THREAD

**Issue by lukyanoffpashok** [yegor256/aibolit#447]

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@586d9f4c-3ecc-4a70-b164-2390bfcb7afb, thread: PQ-CT5UB7XAP
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:Evaluate pattern on arbitary AST' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
```

[0.53.15](https://github.com/zerocracy/farm): CID: [4d0475d9-6181-449d-ba74-059aef7e2a2f](https://www.0crat.com/footprint/CT5UB7XAP/4d0475d9-6181-449d-ba74-059aef7e2a2f), Type: "Job milestoned"

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#447` is not assigned, can't get performer
