### ISSUE TITLE
Need to write console program

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#47]
Need to write console program which will find all patterns and show the most important one.
Also, need to make program compilation with all modules embedded

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT5UB7XAP) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#47` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
