### ISSUE TITLE
first simple metric-finding object

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#5]
Let's implement the first simple `LocMetric` class, which will return the number of lines of code from a java class. Let's place it into `aibolit/metrics/loc`. Let's make sure we have it covered with unit tests, static analysis, and coverage control.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) I'm not managing this repo, remove the [webhook](https://github.com/yegor256/aibolit/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `yegor256/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.2`

**Comment by 0crat** [comment]
I'm not managing `yegor256/aibolit` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.2`
