### ISSUE TITLE
Instance Of usage

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#54]
Need to find _instanceof_  and _.isInstance()_ usage

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@lyriccoder[/z](https://www.0crat.com/u/lyriccoder) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT5UB7XAP) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#54` is not assigned, can't get performer
