### ISSUE TITLE
Merge.py doesn't merge pmd_metrics.py

### ISSUE THREAD

**Issue by lyriccoder** [yegor256/aibolit#67]
Merge.py doesn't merge pmd_metrics.py

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@cbab2ca4a324, thread: pool-5076-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to yegor256/aibolit#67: @yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue
```

[0.51.12](https://github.com/zerocracy/farm): Issue: yegor256/aibolit#67, Action: `reopened`

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#67` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#67` is not assigned, can't get performer
