### ISSUE TITLE
Create download java repositories script

### ISSUE THREAD

**Issue by zuoqin** [yegor256/aibolit#7]
Create a script to:
1. Download trending java repositories first 100
2.  git clone to local
3.  find .java files length > 50 and < 300 lines
4.  output list of paths to such files

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@zuoqin[/z](https://www.0crat.com/u/zuoqin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT5UB7XAP) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#7` is not assigned, can't get performer
