### ISSUE TITLE
Refactor the code

### ISSUE THREAD

**Issue by acheshkov** [yegor256/aibolit#85]
https://github.com/yegor256/aibolit/blob/5322a63aeb1d6840c2094b143dc7c7b3a939526c/aibolit/patterns/this_finder/this_finder.py#L33

Get rid of the flake exception. Reduce the complexity of the source code.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by acheshkov** [comment]
@lukyanoffpashok please look into

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#85` is not assigned, can't get performer
