### ISSUE TITLE
README is broken

### ISSUE THREAD

**Issue by victornoel** [yegor256/aibolit#88]
I run:
```
$ ~/.local/bin/aibolit src/main/java 
usage: aibolit [-h] [--filename FILENAME] [--version]
aibolit: error: unrecognized arguments: src/main/java
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@acheshkov please take a look

**Comment by 0crat** [comment]
The job [#88](https://github.com/yegor256/aibolit/issues/88) assigned to @acheshkov[/z](https://www.0crat.com/u/acheshkov), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/6ea105da-eb86-4573-be04-9f296cd69f40); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @acheshkov[/z](https://www.0crat.com/u/acheshkov) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by lyriccoder** [comment]
Hi @victornoel 
You should run this way as it is explained in help:
`aibolit --filename File.java`

or `aibolit --version`

**Comment by victornoel** [comment]
@lyriccoder I think the README should be fixed

**Comment by victornoel** [comment]
@lyriccoder or the binary so that things happen like in the README, I suppose @yegor256 would decide between the two.

**Comment by lyriccoder** [comment]
@victornoel  We will fix it in Readme

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @acheshkov[/z](https://www.0crat.com/u/acheshkov) is the architect now

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) this job was assigned to you 8days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) I see that you unassigned this issue; the order is still assigned to @acheshkov[/z](https://www.0crat.com/u/acheshkov) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by acheshkov** [comment]
@lyriccoder Have it been fixed already?

**Comment by 0crat** [comment]
The job [#88](https://github.com/yegor256/aibolit/issues/88) assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/92ec4cd9-cb40-4373-b312-6e30a31b10ee); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by victornoel** [comment]
@lyriccoder you are lucky I saw that it was fixed, but next time please notify me so that I can close the ticket when the job is done.
