### ISSUE TITLE
er_class pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#91]
If a class name is one of the following (or ends with this word), it's the pattern:

```
Manager, Controller, Router, Dispatcher, Printer, Writer,
Reader, Parser, Generator, Renderer, Listener, Producer,
Holder, Interceptor
```

**Comment by 0crat** [comment]
@acheshkov[/z](https://www.0crat.com/u/acheshkov) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#91` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#91` is not assigned, can't get performer
