### ISSUE TITLE
classic_setter pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#92]
This is the pattern:

```java
class Book {
  private String title;
  void setTitle(String) {
    this.title = t;
  }
}
```

The method's name starts with `set`, then goes the name of the attribute. The only statement in the method's body is the assignment of the attribute.

**Comment by silverCase** [comment]
are these recognized as valid(as classic_setter) patterns ?

    public Builder setScope(AclEntryScope scope) {
      this.scope = scope;
      return this;
    }
------------------------------------------------------------------
    public Builder setScope(AclEntryScope scope) {
      assert !x;
      this.scope = scope;
    }

**Comment by 0crat** [comment]
The job [#92](https://github.com/yegor256/aibolit/issues/92) assigned to @acheshkov[/z](https://www.0crat.com/u/acheshkov), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/ade15ac6-e7ec-4a54-a542-21e24e88faeb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by yegor256** [comment]
@silverCase no, they are not classic setters

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @acheshkov[/z](https://www.0crat.com/u/acheshkov) is the architect now

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@a8b1883598e0, thread: PQ-CT5UB7XAP
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-boosts.xsl says: The boost for job "gh:yegor256/aibolit#92" exists in boosts.xml, but the job is absent in the WBS among 8 jobs.
```

[0.52](https://github.com/zerocracy/farm): CID: [50bbb9fd-3312-4165-9df8-c4022823c5e7](https://www.0crat.com/footprint/CT5UB7XAP/50bbb9fd-3312-4165-9df8-c4022823c5e7), Type: "Remove job from WBS"
