### ISSUE TITLE
classic_getter pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#94]
This is the pattern:

```java
class Book {
  private String title;
  void getTitle() {
    return this.title;
  }
}
```

The method's name starts with `get`, then goes the name of the attribute. The only statement in the method's body is the return of the attribute.

**Comment by acheshkov** [comment]
@BRZInc

**Comment by silverCase** [comment]
Is this pattern recognized as valid?

```
class Book {
  private String title;
  void getTitle() {
    return title;
  }
}
```

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#94` is not assigned, can't get performer

**Comment by lyriccoder** [comment]
@acheshkov why did u close it? we do not have code for it.
