### ISSUE TITLE
empty_rethrow pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#95]
This is the pattern:

```java
class Book {
  void foo() throws IOException {
    try {
      File.readAllBytes();
    } catch (IOException e) {
      // maybe something else here
      throw e; // here!
    }
  }
}
```

Here we `throw` the same exception.

**Comment by lyriccoder** [comment]
@yegor256 This pattern is A subset of https://github.com/yegor256/aibolit/issues/96

It catches IOException  when throws IOException and then it's rethrown. Should we still focus on it, because it will be very a rare pattern

**Comment by lyriccoder** [comment]
as discussed with @yegor256  the pattern is the following:

```
class Book {
  void foo() {
    try {
      File.readAllBytes();
    } catch (IOException e) {
      // maybe something else here
      throw e; // here!
    }
  }
}
```

**Comment by lyriccoder** [comment]
I am implementing it

**Comment by 0crat** [comment]
Job `gh:yegor256/aibolit#95` is not assigned, can't get performer
