### ISSUE TITLE
redundant_catch pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#96]
Here it is:

```java
class Book {
  void foo() throws IOException {
    try {
      Files.readAllBytes();
    } catch (IOException e) { // here
      // do something
    }
  }
}
```

Here, the method `foo()` throws `IOException`, but we catch it inside the method.

**Comment by lyriccoder** [comment]
assign it to me @0crat

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/aibolit/issues/96#issuecomment-602461563); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by lyriccoder** [comment]
@0crat assign to me

**Comment by 0crat** [comment]
You must be invited in order to do that, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by 0crat** [comment]
The job [#96](https://github.com/yegor256/aibolit/issues/96) assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/6a6851f4-5efb-41e0-8223-dd73819dd2a4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @yegor256[/z](https://www.0crat.com/u/yegor256) is not at this role anymore; @acheshkov[/z](https://www.0crat.com/u/acheshkov) is the architect now
