### ISSUE TITLE
return_null pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#97]
Here it is:

```java
class Book {
  String foo() {
    return null;
  }
}
```

When we return `null`, it's a pattern.

**Comment by lyriccoder** [comment]
@0crat assign to @lyriccoder

**Comment by 0crat** [comment]
You must be invited in order to do that, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by acheshkov** [comment]
@0crat in

**Comment by acheshkov** [comment]
@0crat assign @lyriccoder

**Comment by 0crat** [comment]
> @0crat assign @lyriccoder  ([here](https://github.com/yegor256/aibolit/issues/97#issuecomment-603887382))

@acheshkov The job [#97](https://github.com/yegor256/aibolit/issues/97) assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/36b9afe9-9e42-4827-b4a2-625f910d8576); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by acheshkov** [comment]
Thx

**Comment by 0crat** [comment]
Job was finished in 18 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
