### ISSUE TITLE
partial_synchronized pattern

### ISSUE THREAD

**Issue by yegor256** [yegor256/aibolit#98]
Here it is:

```java
class Book {
  private int a;
  void foo() {
    synchronized (this.a) {
      this.a = 2;
    }
    this.a = 1; // here!
  }
}
```

Here, the `synchronized` block doesn't include all statements of the method. Something stays out of the block.

**Comment by lyriccoder** [comment]
I am implemented it

**Comment by 0crat** [comment]
The job [#98](https://github.com/yegor256/aibolit/issues/98) assigned to @lyriccoder[/z](https://www.0crat.com/u/lyriccoder), here is [why](https://www.0crat.com/footprint/CT5UB7XAP/0a889e39-92d5-43f9-927c-43afe579c662); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @lyriccoder[/z](https://www.0crat.com/u/lyriccoder) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job
